package practicaFinal.Mensajes;

/*
 * Declaro esta clase para que sea más fácil identificar el tipo de los mensajes.
 */
public enum TiposMensaje {
	MENSAJE_CONEXION, MENSAJE_CONFIRMACION_CONEXION, MENSAJE_LISTA_USUARIOS, MENSAJE_CONFIRMACION_LISTA_USUARIOS,
	MENSAJE_PEDIR_FICHERO, MENSAJE_PREPARADO_CLIENTE_SERVIDOR, MENSAJE_PREPARADO_SERVIDOR_CLIENTE,
	MENSAJE_CERRAR_CONEXION, MENSAJE_CONFIRMACION_CERRAR_CONEXION, MENSAJE_EMITIR_FICHERO, MENSAJE_FICHERO_NO_ENCONTRADO
}
